### ISSUE TITLE
Issues with logging

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/rosetta#10]
Server logging is borked due to parsing errors. We get many log4j WARNs on startup:

```
log4j:WARN Continuable parsing error 3 and column 135
log4j:WARN Attribute "xmlns:log4j" with value "http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/xml/doc-files/log4j.dtd" must have a value of "http://jakarta.apache.org/log4j/".
log4j:WARN Continuable parsing error 30 and column 12
log4j:WARN The content of element type "logger" must match "(param*,level?,appender-ref*)".
log4j:WARN Continuable parsing error 35 and column 12
log4j:WARN The content of element type "logger" must match "(param*,level?,appender-ref*)".
log4j:WARN Continuable parsing error 40 and column 12
...
```

Maybe switch from an xml based logger configuration to a [properties based](https://logging.apache.org/log4j/2.x/manual/configuration.html#Configuration_with_Properties) logging configuration?

**Comment by oxelson** [comment]
Added slf4j-* to build.gradle to address the "org.slf4j.impl.StaticLoggerBinder class could not be loaded into memory" errors.  

Also, changed the order of the xml in the log4j.xml file to address the (silly!) .dtd warning errors we were getting in the logs at startup.

1) The order needs to be:
```
<logger>
      <level />
      <appender-ref />
</logger>
```

Else, that validator will whine with the dreaded 
`log4j:WARN The content of element type "logger" must match "(param*,level?,appender-ref*)".`

2) Moved the following elements to the end of the file directly above the closing `</log4j:configuration>`:
```
<root>
    <level/>
    <appender-ref/>
</root>
```
To address this validation error: 
 `log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)"`

OK, so no more log4j errors are being reported in the logs.  This was an easy fix.  We can look at moving to the properties based configuration in the future.
