### ISSUE TITLE
Bug on Windows running a path as regex

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#19]
On Windows, paths have the '\' character, which is used as escape character causing an issue.

Specifically in TemplateController.parseFile:

This causes an error when uploading files (line 396-397):
```
return fileOut.replaceAll(downloadDir+ "/", "") + "\n"
    + jsonOut.replaceAll(downloadDir+ "/", "");
```

**Comment by aleksandervines** [comment]
I believe this should fix it:

```
String escapedDownloadDir = StringEscapeUtils.escapeJava(downloadDir+File.separator);
String out = fileOut.replaceAll(escapedDownloadDir, "") + "\n"
    + jsonOut.replaceAll(escapedDownloadDir, "");
```

**Comment by lesserwhirls** [comment]
We've only been developing on OSX and Linux, so there may be a few more of these lying around. Thanks for the code snippet!
