### ISSUE TITLE
_platformMetadata _coordinateVariable _columnId _coordinateVariableType

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#29]
I think I understand what these variable attributes are, but I'm wondering why they are needed?

They seem to be Rosetta specific. I can see that they might be useful when debugging Rosetta, but not for more than that? In my opinion, having the Rosetta variable should be documentation enough on Rosetta.

**Comment by lesserwhirls** [comment]
No longer using session s in storage this way, and is now part of the template object.
