### ISSUE TITLE
Empty line in header causes parsing error

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/rosetta#3]
When an empty line is present in the header:

header1
header2

header3
data1
data2
data3
...

This is different than the case where no header is present in the file.

The interface does not allow the user to specify metadata for the variables. It looks like an empty line embedded in the header causes a parsing error on the backend.

An example file can be found here: [301-1984CY.txt](https://github.com/Unidata/rosetta/files/193802/301-1984CY.txt)

.

**Comment by oxelson** [comment]
Added process to detect and warn the user that the uploaded file contains blank lines.  Back-end parsing ignores the blank lines and omits them from the display.
