### ISSUE TITLE
Bug - User can click next with nothing selected on "specify header lines"

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#35]
If you firt select a line, then deselect it so that no lines are selected, the user can still click next.

I can see two good solutions: when the last line is deselected either disable next , or check off "no header lines". I think I'd prefer the latter.

Another option would be to simply not allow the last to be deselected unless you check off "no header lines".

**Comment by aleksandervines** [comment]
The same is also the case when "undoing" a variable attributes specification. Reproducable by first specifying all variables so that the next button appears. Then select one of the used variables (not one of those that you've selected not to use)  and instead of pressing done, press the 'x'.

**Comment by lesserwhirls** [comment]
Fixed in the new interface.
