### ISSUE TITLE
faux

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#36]
What is the reason behind the faux button? 

The option I would go for would be to just disable/enable the next button and control the visual effect with simple css.

**Comment by lesserwhirls** [comment]
@oxelson - do you remember why we went with the faux button?

**Comment by oxelson** [comment]
Not really.  Changing the way it's handled as suggested by @aleksandervines would be an improvement.

**Comment by lesserwhirls** [comment]
Addressed in new interface design.
