### ISSUE TITLE
HH:MM:ss

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#40]
Is that a valid "time only" unit? I thought capital M was month.

Ref unit builder for time only.

**Comment by aleksandervines** [comment]
Also, according to CF, units must be recognized by your udunits package, with a few exceptions. I don't think this practice with the time units builder follows that? As I can see from the grammar, clock is part of timestamp which is a part of unit-spec, but can not stand alone.

Does this perhaps count as dimensionless and can stand without units, but explained in the long_name (per exception rule in CF)?

**Comment by lesserwhirls** [comment]
You're correct - this is a typo (`MM` should be `mm`). The idea here is that some older dataloggers separate date and time (clock) values in their CSV files, so the interface was setup to allow those two pieces to be entered and defined separately. Behind the scenes, these two values are used to compute a time that is UDUNITS compliant.
