### ISSUE TITLE
Java coding style

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#42]
I'm wondering if there are any specified coding style that you have defined? I supposed you are using the same all over at Unidata, but I can not see this specified in e.g. the Thredds repo either.

From what I can see, you use 4 spaces indentation (although not 100% consistent, as there are some tabs around), there seems to be no, or a high, column limit and you use unix line delimiters. The file encoding is US-ASCII.

But there are a lot more in a style/coding convention. Do you got it documented?

And what about javascript?

**Comment by lesserwhirls** [comment]
Hi @aleksandervines - there isn't a coding style specified for this, and we don't really have one for overall use in the Unidata organization. I am certainly not opposed to having one, though! I would propose the use of the [Google style](https://google.github.io/styleguide/javaguide.html), but only because it's already defined and there are several IDE [style configs](https://github.com/google/styleguide) for it. I'm am open to suggestions though.

**Comment by DennisHeimbigner** [comment]
We could begin to experiment with this individually.
Would help if we had a google style we could import
into Intellij.

**Comment by lesserwhirls** [comment]
Yeah, google keeps their style settings on github (see link in my post above). I'm more fond of 4 spaces as well, but I could get used to 2 for the sake of using the default google style.

**Comment by aleksandervines** [comment]
Google style sound good! Though I would also prefer 4 spaces.

Do you want to make this style change gradually on entire files when they are updated, or just new code blocks, or on the entire project at once as one big commit?

This means the file encoding for the entire project should change to UTF-8 though? But I guess that should all happen at once? I don't have the best experience in mixing encoding environment.

**Comment by lesserwhirls** [comment]
Ok, I updated the styles for intellij and eclipse to use 4 spaces instead of 2. Also, these include the styles for javascript, so we should be good there. I think we should do all of the changes at once in one commit.

**Comment by aleksandervines** [comment]
Google uses their c++ style as base for Javascript.
I'm not sure how much it differs from their java one, but they have two different xml files for these as far as I can see.

https://google.github.io/styleguide/javascriptguide.xml#Code_formatting
> We follow the C++ formatting rules in spirit, with the following additional clarifications.

**Comment by lesserwhirls** [comment]
It looks like there is a separate C++ style for eclipse, but there are options in the intellij file to style javascript (so all in one). I'll add the C++ style for eclipse and update the indentation.

**Comment by aleksandervines** [comment]
Not sure if this belongs here,  #46, #50 or #53 but all are closed.

You have not changed the javascript code according to the style spec. E.g. Google c++ spec (and javscript guide) has a max line width of 80, you seem to have applied 100, which is what they use for Java. I don't know if there are other differences. Not that I complain about that detail, I think both 80 and 100 is too low compared to what you can fit on (half) a modern screen, this requirement seems outdated for me.

Also, I'm not convinced that the java style is applied properly on eclipse, as a warning pops up (seems to be the case since eclipse luna edition).  https://github.com/google/styleguide/issues/33
