### ISSUE TITLE
Set maxUploadSize property from a single location

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/rosetta#6]
Currently, the MaxUploadSize is defined in two places:

rosetta-servlet.xml

  
  <bean id="multipartResolver" class="org.springframework.web.multipart.commons.
                 CommonsMultipartResolver">
      <property name="maxUploadSize" value="1048576"/>
  </bean>

and validationFunctions.js:

    if ((file.size / 1024) > 1024) {
        $(errorLabel).text("Error! File size should be less then 1MB");
        $("#upload").addClass("hideMe");
        boolean = false;
    } else {

This should be able to be overwritten by a property in rosettaConfig.properties?

**Comment by oxelson** [comment]
maxUploadSize is now defined in WEB-INF/classes/defaultRosettaConfig.properties  and is used for both front and backend validation:

- Added PropertyPlaceholderConfigurer class in rosetta-servlet.java for properties injection.  Makes this attribute available to Spring CommonsMultipartResolver.
- Modified RosettaProperties.java utils class glean this value from .properties and TemplateController.java to pass it to client-side model.   Client-side javascript uses this value for validation.

**Comment by aleksandervines** [comment]
I believe you've forgot 

`model.addAttribute("maxUploadSize", RosettaProperties.getMaxUploadSize(servletContext));`

in TemplateController for the /restore mapping

**Comment by oxelson** [comment]
Yep, your absolutely right.  I'll have a look.  Thanks for spotting this!
