### ISSUE TITLE
CF compliance issues

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#68]
I have discovered two cf-compliance issues.

1. The only attribute name which is allowed to start with an underscore is _FillValue
2. The variable which the cf_role attribute is attached to should be a coordinate variable.

These requirements were new to me, and, in my opinion, not clear from the documentation. But after a mail correspondence with the creator of the "official" CF-compliance checker, and her verifying this with some of the authors of the CF-convention, I'm convinced.

Also, there has been a defect in CF 1.6 were the examples were wrong on the second issue, this has been fixed in the 1.7 draft, but that was were my misconception on the cf_role originated from.

**Comment by lesserwhirls** [comment]
Interesting - thanks for the heads-up @aleksandervines!

I didn't know underscore attributes were forbidden in CF. I was using the underscore attributes for rosetta specific metadata. I can simple replace the underscores with `rosetta_ATTR`, so that should be no problem. As for point 2, changing the variable to which cf_role is attached to a coordinate variable shouldn't be an issue. I'll get these fixes in today.

**Comment by DennisHeimbigner** [comment]
This better not be the case because other attributes exist
that have a leading underscore. The rule is that names
(including attributes) that begin with an underscore are
reserved for the use of unidata.
=Dennis Heimbigner
  Unidata

**Comment by aleksandervines** [comment]
Well, I'm just forwarding the information I got, which was:

> I've just been speaking to one of the CF authors and he says it is a requirement that attributes, variables and dimensions start with a letter with the exception of _FillValue.  I have raised a ticket to propose a clarification to the standard and now await comments.

The documentation does state "The netCDF interface also allows leading underscores in names, but the NUG states that this is reserved for system use." Which is why I first raised this issue for them as I believed it to be an error in one of the compliance checkers they've linked to - http://puma.nerc.ac.uk/cgi-bin/cf-checker.pl

Whether or not this "should be the case" is perhaps something Unidata should clarify with them?

**Comment by aleksandervines** [comment]
Ref this: http://cf-trac.llnl.gov/trac/ticket/157

**Comment by DennisHeimbigner** [comment]
Thanks for pointing this out. We will see what we can do.
=Dennis Heimbigner
  Unidata

**Comment by lesserwhirls** [comment]
We no longer use underscore variables in the converted netCDF files, so we should be good now.
