### ISSUE TITLE
Standard attribute names

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#69]
The metadata you add does not seem to follow a standard I know of.

E.g. the main standard I'd like to follow would be ACDD, which would change e.g. these attributes:
description->summary
dataAuthor->creator_name +add: creator_email, creator_url
dataSource->source, platform(_vocabulary), instrument(_vocabulary),
version->product_version
and add all missing ones as recommended/optional

Ref the two following pages:
http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/metadata/DataDiscoveryAttConvention.html
http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery

This is also mentioned in #16 but I think this should be its own issue.

**Comment by lesserwhirls** [comment]
The wizard interface is now driven by ACDD metadata, so this should be good now.
