### ISSUE TITLE
Delimiter defined in multiple places

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/rosetta#9]
The set of potential delimiters is defined in multiple places:

delimiters.xml
AsciiFile.convertDelimiters()

it would be good to have one place where potential delimiters are defined.

**Comment by aleksandervines** [comment]
I would also suggest not to hard code the delimiters into the code as it is now in AsciiFile.java

**Comment by oxelson** [comment]
All delimiter access now performed via database query.
